'use client';

// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import {
	QueryClient,
	QueryClientProvider,
	useQuery,
} from '@tanstack/react-query';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const queryClient = new QueryClient();

	return (
		<html lang="en">
			<QueryClientProvider client={queryClient}>
				<body className={inter.className}>
					<Navbar />
					<main className="min-h-screen bg-gray-100">{children}</main>
				</body>
			</QueryClientProvider>
		</html>
	);
}
